### ISSUE TITLE
lme4 versioning

### ISSUE THREAD

**Issue by mcfrank** [manybabies/mb1-analysis-public#1]
Note that convergence pruning for this draft was done with lme4 v1.1-13, but with versions 1.1-19, @angelinetsui reports singularity (but not convergence) warning. minimally we need to set up some version compliance for the ms, but it's also possible we should think about updating the pruning for the final version. 

thoughts @christinabergmann @mekline @melsod?

**Comment by christinabergmann** [comment]
To begin with, we should note the version in the final MS and add some language to the code about versioning and possible effects thereof. 
I am not sure we need to update the model in the paper, but remain neutral on this issue (my main counter argument is to avoid additional rounds of review due to changing stats, because the analyses were done  correctly given the available version).

**Comment by mcfrank** [comment]
I have updated the model and noted the version in the ms.
